name: PartyHub Actions
on: [push]
jobs:
  Build-PartyHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: 'partyhub/pom.xml'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
